using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProjectLucy.Infrastructure.Persistence.Migrations;

/// <summary>
/// Repairs databases created by the older payment migrations. Those migrations
/// recorded a model snapshot that was ahead of the SQL they actually applied.
/// </summary>
public partial class AddWalletAndCommerceSchema : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE EXTENSION IF NOT EXISTS pgcrypto;

            -- Keep the legacy payment table, if present, so this repair cannot
            -- destroy historical payment data.

            CREATE TABLE IF NOT EXISTS "role_price" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "role_id" integer NOT NULL,
                "price" numeric(12,2) NOT NULL,
                "currency" varchar(10) DEFAULT 'VND',
                "duration" interval,
                "description" text,
                "is_active" boolean DEFAULT true,
                "created_at" timestamptz DEFAULT now(),
                "updated_at" timestamptz DEFAULT now(),
                CONSTRAINT "role_price_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role" ("role_id")
            );

            CREATE TABLE IF NOT EXISTS "gift_catalog" (
                "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                "name" varchar(100) NOT NULL,
                "description" text,
                "icon_url" text,
                "price" numeric(10,2) NOT NULL,
                "currency" varchar(10) NOT NULL DEFAULT 'VND',
                "is_active" boolean NOT NULL DEFAULT true,
                "created_at" timestamptz NOT NULL DEFAULT now(),
                "updated_at" timestamptz NOT NULL DEFAULT now()
            );

            CREATE TABLE IF NOT EXISTS "transaction_type" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "code" varchar(50) NOT NULL,
                "name" varchar(100) NOT NULL,
                "description" text,
                "is_active" boolean DEFAULT true,
                "created_at" timestamptz DEFAULT now(),
                "updated_at" timestamptz DEFAULT now()
            );

            CREATE TABLE IF NOT EXISTS "wallet" (
                "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                "user_id" uuid NOT NULL,
                "balance" numeric(15,2) NOT NULL DEFAULT 0.00,
                "currency" varchar(10) NOT NULL DEFAULT 'VND',
                "created_at" timestamptz NOT NULL DEFAULT now(),
                "updated_at" timestamptz NOT NULL DEFAULT now(),
                CONSTRAINT "fk_wallet_user" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "transactions" (
                "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "transaction_type_id" integer NOT NULL,
                "user_id" uuid NOT NULL,
                "amount" numeric(15,2) NOT NULL,
                "currency" varchar(10) DEFAULT 'VND',
                "transaction_content" text,
                "status" varchar(20) DEFAULT 'pending',
                "reference_code" varchar(100),
                "created_at" timestamptz DEFAULT now(),
                "updated_at" timestamptz DEFAULT now(),
                CONSTRAINT "fk_transactions_user" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id"),
                CONSTRAINT "transactions_transaction_type_id_fkey" FOREIGN KEY ("transaction_type_id") REFERENCES "transaction_type" ("id")
            );

            CREATE TABLE IF NOT EXISTS "gift_transaction" (
                "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                "transaction_id" bigint NOT NULL,
                "sender_id" uuid NOT NULL,
                "receiver_id" uuid NOT NULL,
                "gift_id" uuid NOT NULL,
                "room_session_id" uuid,
                "quantity" integer NOT NULL DEFAULT 1,
                "total_value" numeric(10,2) NOT NULL,
                "created_at" timestamptz NOT NULL DEFAULT now(),
                CONSTRAINT "fk_gift_txn_gift" FOREIGN KEY ("gift_id") REFERENCES "gift_catalog" ("id"),
                CONSTRAINT "fk_gift_txn_receiver" FOREIGN KEY ("receiver_id") REFERENCES "user" ("user_id"),
                CONSTRAINT "fk_gift_txn_sender" FOREIGN KEY ("sender_id") REFERENCES "user" ("user_id"),
                CONSTRAINT "fk_gift_txn_transaction" FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id")
            );

            CREATE TABLE IF NOT EXISTS "payment_method" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "transaction_id" bigint NOT NULL,
                "provider" varchar(50) NOT NULL,
                "provider_txn_id" varchar(255),
                "raw_status" varchar(50),
                "metadata" jsonb,
                "paid_at" timestamptz,
                "created_at" timestamptz NOT NULL DEFAULT now(),
                "updated_at" timestamptz NOT NULL DEFAULT now(),
                CONSTRAINT "fk_payment_method_transaction" FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "role_upgrade_order" (
                "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                "transaction_id" bigint NOT NULL,
                "user_id" uuid NOT NULL,
                "from_role_id" integer NOT NULL,
                "to_role_id" integer NOT NULL,
                "role_price_id" integer NOT NULL,
                "activated_at" timestamptz,
                "expires_at" timestamptz,
                "cancelled_at" timestamptz,
                "created_at" timestamptz NOT NULL DEFAULT now(),
                "updated_at" timestamptz NOT NULL DEFAULT now(),
                CONSTRAINT "fk_upgrade_from_role" FOREIGN KEY ("from_role_id") REFERENCES "role" ("role_id"),
                CONSTRAINT "fk_upgrade_role_price" FOREIGN KEY ("role_price_id") REFERENCES "role_price" ("id"),
                CONSTRAINT "fk_upgrade_to_role" FOREIGN KEY ("to_role_id") REFERENCES "role" ("role_id"),
                CONSTRAINT "fk_upgrade_transaction" FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id"),
                CONSTRAINT "fk_upgrade_user" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id")
            );

            CREATE TABLE IF NOT EXISTS "wallet_ledger" (
                "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "wallet_id" uuid NOT NULL,
                "transaction_id" bigint NOT NULL,
                "amount" numeric(15,2) NOT NULL,
                "balance_after" numeric(15,2) NOT NULL,
                "entry_type" text NOT NULL,
                "note" text,
                "created_at" timestamptz NOT NULL DEFAULT now(),
                CONSTRAINT "fk_ledger_transaction" FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id"),
                CONSTRAINT "fk_ledger_wallet" FOREIGN KEY ("wallet_id") REFERENCES "wallet" ("id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "role_price_role_id_key" ON "role_price" ("role_id", "id");
            CREATE INDEX IF NOT EXISTS "idx_role_price_active" ON "role_price" ("is_active");
            CREATE INDEX IF NOT EXISTS "idx_role_price_role_id" ON "role_price" ("role_id");
            CREATE INDEX IF NOT EXISTS "idx_gift_catalog_active" ON "gift_catalog" ("is_active");
            CREATE UNIQUE INDEX IF NOT EXISTS "transaction_type_code_key" ON "transaction_type" ("code");
            CREATE INDEX IF NOT EXISTS "idx_transaction_type_code" ON "transaction_type" ("code");
            CREATE UNIQUE INDEX IF NOT EXISTS "wallet_user_id_key" ON "wallet" ("user_id");
            CREATE INDEX IF NOT EXISTS "idx_transactions_created_at" ON "transactions" ("created_at");
            CREATE INDEX IF NOT EXISTS "idx_transactions_reference_code" ON "transactions" ("reference_code");
            CREATE INDEX IF NOT EXISTS "idx_transactions_status" ON "transactions" ("status");
            CREATE INDEX IF NOT EXISTS "idx_transactions_type_id" ON "transactions" ("transaction_type_id");
            CREATE INDEX IF NOT EXISTS "idx_transactions_user_id" ON "transactions" ("user_id");
            CREATE UNIQUE INDEX IF NOT EXISTS "transactions_reference_code_key" ON "transactions" ("reference_code");
            CREATE UNIQUE INDEX IF NOT EXISTS "gift_transaction_transaction_id_key" ON "gift_transaction" ("transaction_id");
            CREATE INDEX IF NOT EXISTS "idx_gift_txn_receiver" ON "gift_transaction" ("receiver_id", "created_at" DESC);
            CREATE INDEX IF NOT EXISTS "idx_gift_txn_sender" ON "gift_transaction" ("sender_id", "created_at" DESC);
            CREATE INDEX IF NOT EXISTS "idx_gift_txn_session" ON "gift_transaction" ("room_session_id");
            CREATE INDEX IF NOT EXISTS "idx_payment_method_provider" ON "payment_method" ("provider");
            CREATE INDEX IF NOT EXISTS "idx_payment_method_provider_txn" ON "payment_method" ("provider_txn_id");
            CREATE UNIQUE INDEX IF NOT EXISTS "payment_method_transaction_id_key" ON "payment_method" ("transaction_id");
            CREATE INDEX IF NOT EXISTS "idx_upgrade_active" ON "role_upgrade_order" ("user_id", "expires_at")
                WHERE "activated_at" IS NOT NULL AND "cancelled_at" IS NULL;
            CREATE INDEX IF NOT EXISTS "idx_upgrade_user" ON "role_upgrade_order" ("user_id", "created_at" DESC);
            CREATE UNIQUE INDEX IF NOT EXISTS "role_upgrade_order_transaction_id_key" ON "role_upgrade_order" ("transaction_id");
            CREATE INDEX IF NOT EXISTS "idx_wallet_ledger_txn" ON "wallet_ledger" ("transaction_id");
            CREATE INDEX IF NOT EXISTS "idx_wallet_ledger_wallet" ON "wallet_ledger" ("wallet_id", "created_at" DESC);

            INSERT INTO "role" ("role_id", "role_code", "role_name", "created_at", "updated_at")
            VALUES (1, 'LUCY', 'Lucy User', now(), now()),
                   (2, 'PRO', 'Pro User', now(), now()),
                   (3, 'SUPER', 'Super User', now(), now())
            ON CONFLICT ("role_code") DO NOTHING;

            INSERT INTO "transaction_type" ("code", "name", "description", "is_active", "created_at", "updated_at")
            VALUES ('ONLINE_SEPAY', 'SePay Online Payment', 'Payment made online through SePay', true, now(), now()),
                   ('ROLE_UPGRADE_SEPAY', 'SePay Role Upgrade', 'Role upgrade through SePay', true, now(), now()),
                   ('GIFT_SEND', 'Gift Sent', 'Gift sent by a user', true, now(), now()),
                   ('GIFT_RECEIVE', 'Gift Received', 'Gift received by a user', true, now(), now())
            ON CONFLICT ("code") DO NOTHING;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // This repair migration is intentionally non-destructive on rollback.
    }
}
